name: ziti-webhook
on: 
  create:
  delete:
  issues:
  issue_comment:
  pull_request_review:
  pull_request_comment:
  pull_request:
  pushi:
  fork:
  releases:

jobs:
  ziti-webhook:
    runs-on: macos-latest
    name: Ziti Webhook
    steps:
    - uses: openziti/ziti-webhook-action@main
      with:
        ziti-id: ${{ secrets.ZITI_MATTERMOST_IDENTITY }}
        webhook-url: ${{ secrets.ZITI_MATTERMOST_WEBHOOK_URL }}
        webhook-secret: ${{ secrets.ZITI_MATTERMOSTI_WEBHOOK_SECRET }}
